[package]
name = "access-control"
version = "0.1.1"
authors = ["Dan Henton"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/WunderbarNetwork/access-control"

[dependencies]
log = { default-features = false, version = "0.4" }
scale-info = { version = '2.3.0', default-features = false, features = [
    'derive',
] }
codec = { version = '3.2.1', default-features = false, features = [
    'derive',
], package = 'parity-scale-codec' }
serde = { version = "1.0.130" }

sp-core = { version = '7.0.0', default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.43" }
sp-io = { version = '7.0.0', default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.43" }
sp-runtime = { version = "7.0.0", default-features = false, git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.43" }
sp-std = { version = '5.0.0', default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.43" }
frame-benchmarking = { version = '4.0.0-dev', default-features = false, git = 'https://github.com/paritytech/substrate.git', optional = true, branch = "polkadot-v0.9.43" }
frame-support = { version = '4.0.0-dev', default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.43" }
frame-system = { version = '4.0.0-dev', default-features = false, git = 'https://github.com/paritytech/substrate.git', branch = "polkadot-v0.9.43" }

[dev-dependencies]
test-context = { default-features = false, version = "0.1.4" }

[features]
default = ['std']
runtime-benchmarks = ['frame-benchmarking']
std = [
    'codec/std',
    'frame-benchmarking/std',
    'frame-support/std',
    'frame-system/std',
    'scale-info/std',
    'sp-core/std',
    'sp-io/std',
    'sp-std/std',
    'sp-runtime/std',
    'serde/std',
]
try-runtime = ['frame-support/try-runtime']
